-- Migration: create Véhicule table
-- Created: 2026-06-02

CREATE TABLE IF NOT EXISTS public."Véhicule" (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  immatriculation character varying NULL,
  marque character varying NULL,
  modele character varying NULL,
  couleur character varying NULL,
  "typeVehicule" character varying NULL,
  CONSTRAINT "Véhicule_pkey" PRIMARY KEY (id)
) TABLESPACE pg_default;
