-- Migration: create trajets table for driver routes
-- Created: 2026-06-02

CREATE TABLE IF NOT EXISTS public.trajets (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  id_chauffeur uuid NOT NULL,
  point_depart character varying NOT NULL,
  point_destination character varying NOT NULL,
  heure_depart time without time zone NOT NULL,
  heure_arrivee time without time zone NOT NULL,
  prix_estime numeric(10,2) NOT NULL DEFAULT 0,
  description text NULL,
  CONSTRAINT trajets_pkey PRIMARY KEY (id),
  CONSTRAINT trajets_id_chauffeur_fkey FOREIGN KEY (id_chauffeur) REFERENCES public.profiles(id) ON DELETE CASCADE
) TABLESPACE pg_default;

-- Create index on id_chauffeur for faster queries
CREATE INDEX IF NOT EXISTS idx_trajets_id_chauffeur ON public.trajets (id_chauffeur);
