-- Migration: create colis table for package delivery
-- Created: 2026-06-02

CREATE TABLE IF NOT EXISTS public.colis (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  id_client uuid NOT NULL,
  point_depart character varying NOT NULL,
  point_destination character varying NOT NULL,
  description text NOT NULL,
  poids numeric(8,2) NOT NULL DEFAULT 0,
  prix_offert numeric(10,2) NOT NULL DEFAULT 0,
  statut character varying NOT NULL DEFAULT 'en_attente',
  id_chauffeur uuid NULL,
  CONSTRAINT colis_pkey PRIMARY KEY (id),
  CONSTRAINT colis_id_client_fkey FOREIGN KEY (id_client) REFERENCES public.profiles(id) ON DELETE CASCADE,
  CONSTRAINT colis_id_chauffeur_fkey FOREIGN KEY (id_chauffeur) REFERENCES public.profiles(id) ON DELETE SET NULL
) TABLESPACE pg_default;

-- Create index on id_client for faster queries
CREATE INDEX IF NOT EXISTS idx_colis_id_client ON public.colis (id_client);

-- Create index on id_chauffeur for faster queries
CREATE INDEX IF NOT EXISTS idx_colis_id_chauffeur ON public.colis (id_chauffeur);

-- Create index on statut for filtering
CREATE INDEX IF NOT EXISTS idx_colis_statut ON public.colis (statut);
